services:
  # Web service using Dockerfile.web
  - type: web
    name: web
    runtime: docker
    repo: https://github.com/bhargavns/pet-sitting-demo.git
    dockerfilePath: Dockerfile.web
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 60

  # Database service using Dockerfile.db
  - type: pserv
    name: db
    runtime: docker
    repo: https://github.com/bhargavns/pet-sitting-demo.git
    dockerfilePath: Dockerfile.db
    branch: main
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: pwd
      - key: POSTGRES_DB
        value: db
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10

# List of PostgreSQL databases
databases:
  - name: db
    databaseName: db
    user: postgres_user

